# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "" # Leave this blank to use full name as the website title
first_name: Wanwen
middle_name:
last_name: Zeng
email: wanwen@stanford.edu
description: > 
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website
lang: en
icon: "⚛️" # Ensure this emoji works as the favicon (alternative, provide an image path)
url: https://wanwenzeng.github.io
baseurl: ""
last_updated: false 
impressum_path: ""
back_to_top: true 

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default 
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
rss_icon: false 

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
bib_search: true
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image: "" # Add the Open Graph preview image path if needed

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

acm_id: ""
blogger_url: ""
bluesky_url: ""
dblp_url: ""
discord_id: ""
facebook_id: ""
flickr_id: ""
github_username: ""
gitlab_username: ""
ieee_id: ""
inspirehep_id: ""
instagram_id: ""
kaggle_id: ""
keybase_username: ""
lastfm_id: ""
lattes_id: ""
linkedin_username: ""
mastodon_username: ""
medium_username: ""
orcid_id: ""
osf_id: ""
pinterest_id: ""
publons_id: ""
quora_username: ""
research_gate_profile: ""
scholar_userid: MbeOhkgAAAAJ
scopus_id: ""
semanticscholar_id: ""
spotify_id: ""
stackoverflow_id: ""
telegram_username: ""
unsplash_id: ""
wechat_qr: ""
whatsapp_number: ""
wikidata_id: ""
wikipedia_id: ""
work_url: ""
x_username: ""
youtube_id: ""
zotero_username: ""

contact_note: ""

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: "" 
cronitor_analytics: "" 
pirsch_analytics: "" 
google_site_verification: "" 
bing_site_verification: "" 

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: al-folio 
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/
lsi: false 

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

giscus:
  repo: "" 
  repo_id: "" 
  category: Comments 
  category_id: "" 
  mapping: title 
  strict: 1 
  reactions_enabled: 1 
  input_position: bottom 
  theme: preferred_color_scheme 
  emit_metadata: 0
  lang: en

disqus_shortname: al-folio

external_sources:
  - name: medium.com
    rss_url: https://medium.com/@al-folio/feed
  - name: Google Blog
    posts:
      - url: https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/
        published_date: 2024-05-14

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint: ""

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/

announcements:
  enabled: true
  scrollable: true
  limit: 5

latest_posts:
  enabled: true
  scrollable: true
  limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - README.md
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-sitemap
  - jemoji

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Wanwen]
  first_name: [Zeng]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending
  enable_publication_badges:
    altmetric: true
    dimensions: true
    google_scholar: true
    inspirehep: true
  max_author_limit: 3
  more_authors_animation_delay: 10
  enable_publication_thumbnails: true
